// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qphujgdfenhxyniidetd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFwaHVqZ2RmZW5oeHluaWlkZXRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM4NjkzMjksImV4cCI6MjA3OTQ0NTMyOX0.G86KD72Py6YsZsBy5YJGZLwVxStzWVVmK-gvHD5oers";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);