// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://buftwizsvpykrleyvwcf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1ZnR3aXpzdnB5a3JsZXl2d2NmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0MzQ0MjIsImV4cCI6MjA2MjAxMDQyMn0.jXQi_US_kxWW7c6rfc4PjwBlzM_PVOuiL6l7Mj8qfbM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);